"""Write tools/i18n/aspect_names.tsv: every legendary aspect name and the
'OF ...' tail used in legendary item names, from one table of core nouns.
English 'ASPECT OF X' -> zh 'X之威能', ja 'Xの威能', ko 'X의 위상';
tail 'OF X' -> 'X之' / 'Xの' / 'X의' placed before the item base name."""

CORE = {  # english tail: (zh-Hans, zh-Hant, ja, ko)
    'ASCENDANCY': ('优势', '優勢', '優位', '우위'),
    'EXPOSURE': ('暴露', '暴露', '露呈', '노출'),
    'THE KEEN EDGE': ('利刃', '利刃', '鋭刃', '예리한 칼날'),
    'CRUSHING WEIGHT': ('重压', '重壓', '圧殺', '짓누르는 무게'),
    'THE SNARE': ('罗网', '羅網', '罠', '올가미'),
    'LINGERING WOUNDS': ('久伤', '久傷', '残る傷', '남은 상처'),
    'THE HUNT': ('狩猎', '狩獵', '狩り', '사냥'),
    'RECKLESS FURY': ('鲁莽怒火', '魯莽怒火', '無謀な怒り', '무모한 분노'),
    'THE WARDEN': ('守望者', '守望者', '守護者', '수호자'),
    'THE BULWARK': ('壁垒', '壁壘', '防壁', '보루'),
    'RENEWAL': ('新生', '新生', '再生', '재생'),
    'THORNED HIDE': ('荆棘皮', '荊棘皮', '棘の皮', '가시 가죽'),
    'THE UNBROKEN': ('不屈者', '不屈者', '不屈の者', '불굴자'),
    'THE WELLSPRING': ('泉源', '泉源', '泉', '샘'),
    'FRUGALITY': ('节俭', '節儉', '倹約', '검소함'),
    'HASTENED HOURS': ('疾时', '疾時', '早き時', '서두른 시간'),
    'FORTUNE': ('财富', '財富', '幸運', '행운'),
    'THE WANDERER': ('流浪者', '流浪者', '放浪者', '방랑자'),
    'THE BLOODREAVER': ('夺血者', '奪血者', '血奪い', '피약탈자'),
    'THE RAVAGER': ('蹂躏者', '蹂躪者', '蹂躙者', '약탈자'),
    'TECTONIC FISTS': ('地壳拳', '地殼拳', '地殻の拳', '지각의 주먹'),
    'AFTERMATH': ('余波', '餘波', '余波', '여파'),
    'THE THUNDER HAMMER': ('雷锤', '雷錘', '雷鎚', '천둥 망치'),
    'ENDLESS RAGE': ('无尽怒火', '無盡怒火', '尽きぬ怒り', '끝없는 분노'),
    'THE EMBERFALL': ('烬落', '燼落', '燃え殻の雨', '잔불 낙하'),
    'THE CINDER CROWN': ('余烬王冠', '餘燼王冠', '燃え殻の冠', '잿불 왕관'),
    "WINTER'S HEART": ('寒冬之心', '寒冬之心', '冬の心', '겨울의 심장'),
    'THE GLACIER': ('冰川', '冰川', '氷河', '빙하'),
    'THE THUNDERLORD': ('雷霆领主', '雷霆領主', '雷帝', '뇌제'),
    "THE STORM'S EYE": ('风暴之眼', '風暴之眼', '嵐の目', '폭풍의 눈'),
    'THE DUSK LONGBOW': ('黄昏长弓', '黃昏長弓', '黄昏の長弓', '황혼 장궁'),
    'THE HAWK': ('苍鹰', '蒼鷹', '鷹', '매'),
    'THE VIPER': ('毒蛇', '毒蛇', '毒蛇', '독사'),
    'THE QUIVER': ('箭袋', '箭袋', '矢筒', '화살통'),
    'SKYFALL': ('天坠', '天墜', '天落', '하늘 추락'),
    'THE PLAGUEBEARER': ('疫病使者', '疫病使者', '疫病の運び手', '역병 매개자'),
    'THE SPLINTERED SPEAR': ('碎矛', '碎矛', '砕けた槍', '부서진 창'),
    'THE BLIGHTED': ('枯萎者', '枯萎者', '枯死者', '역병 걸린 자'),
    'THE SANGUINE': ('血红', '血紅', '血紅', '혈홍'),
    'THE GRAVE LEGION': ('墓穴军团', '墓穴軍團', '墓の軍団', '무덤 군단'),
    'THE HOLLOW MARROW': ('空洞骨髓', '空洞骨髓', '虚ろな骨髄', '텅 빈 골수'),
    'CORPSE BLOOM': ('尸花', '屍花', '死体の花', '시체 꽃'),
    'THE TEMPEST': ('暴风', '暴風', '大嵐', '폭풍우'),
    'THE MOUNTAIN': ('山岳', '山嶽', '山', '산'),
    'THE PACK LEADER': ('头狼', '頭狼', '群れの長', '우두머리'),
    'THE ROLLING STONE': ('滚石', '滾石', '転がる石', '구르는 돌'),
    'THE MOONLIT CLAW': ('月爪', '月爪', '月光の爪', '달빛 발톱'),
    'THE STORMHIDE': ('暴风兽皮', '暴風獸皮', '嵐の皮', '폭풍 가죽'),
    'THE FOUR WINDS': ('四风', '四風', '四方の風', '사방의 바람'),
    'THE IRON PALM': ('铁掌', '鐵掌', '鉄の掌', '강철 손바닥'),
    'THE VENOM COIL': ('毒环', '毒環', '毒の環', '독의 고리'),
    'THE SWARM': ('虫群', '蟲群', '群れ', '떼'),
    'THE PROWLING JAGUAR': ('潜行美洲豹', '潛行美洲豹', '忍び寄るジャガー', '배회하는 재규어'),
    'THE SKYBORNE': ('翱天者', '翱天者', '天翔ける者', '하늘을 나는 자'),
    'THE STORMCLAW': ('风暴之爪', '風暴之爪', '嵐の爪', '폭풍 발톱'),
    'THE MOONLIT HUNT': ('月下狩猎', '月下狩獵', '月下の狩り', '달빛 사냥'),
    'SPLINTERED BONE': ('碎骨', '碎骨', '砕けた骨', '부서진 뼈'),
    'THE MARROW WELL': ('骨髓之泉', '骨髓之泉', '骨髄の泉', '골수의 샘'),
    'THE FIRESTORM': ('火焰风暴', '火焰風暴', '炎の嵐', '화염 폭풍'),
    'THE PHOENIX': ('凤凰', '鳳凰', '不死鳥', '불사조'),
}

rows = ['// GENERATED by make_aspect_names.py: aspect names and legendary name tails']
for en, (zs, zt, ja, ko) in CORE.items():
    rows.append('\t'.join([f'ASPECT OF {en}', zs + '之威能', zt + '之威能', ja + 'の威能', ko + '의 위상']))
    rows.append('\t'.join([f'OF {en}', zs + '之', zt + '之', ja + 'の', ko + '의']))
open('tools/i18n/aspect_names.tsv', 'w', encoding='utf-8', newline='\n').write('\n'.join(rows) + '\n')
print(len(CORE), 'aspects')
